name: learn-github-actions
on: [push]
jobs:
  check-newman-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g newman
      - run: newman -v
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
